import javascript from "./javascript-icon.svg";
import react from "./react-icon.svg";
import reactNative from "./react-native-icon.svg";
import graphQL from "./graphql-icon.svg";
import vite from "./vite-icon.svg";
import node from "./node-icon.svg";
import docker from "./docker-icon.svg";
import postgresql from "./postgresql-icon.svg";
import typescript from "./typescript-icon.svg";
import nestjs from "./nestjs-icon.svg";
import nextJs from "./next-icon.svg";
import linkedIn from "./linkedin-icon.svg";
import email from "./email-icon.svg";
import github from "./github-icon.svg";

export const javascriptIcon = javascript;
export const reactIcon = react;
export const reactNativeIcon = reactNative;
export const graphQLIcon = graphQL;
export const nodeIcon = node;
export const viteIcon = vite;
export const dockerIcon = docker;
export const postgresqlIcon = postgresql;
export const typescriptIcon = typescript;
export const nestjsIcon = nestjs;
export const nextJsIcon = nextJs;
export const linkedInIcon = linkedIn;
export const emailIcon = email;
export const githubIcon = github;
