on:
  pull_request:
    branches:
      - dev
      - master

  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install NPM Dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Revert merge if fails
        if: ${{ failure() }}
        uses: yashdalfthegray/revert-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}